[project]
name = "mcp-servers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AI2Enginex", email = "vibhorsakalley@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiomysql>=0.3.2",
    "ddgs[mcp]>=9.11.4",
    "fastapi[standard]>=0.141.1",
    "fastmcp==2.14.1",
    "google-genai>=2.20.0",
    "mcp==1.24.0",
    "pandas>=3.0.5",
    "pydantic-settings>=2.15.0",
    "pymysql>=1.2.0",
    "sqlalchemy>=2.0.52",
    "tavily>=1.1.0",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
mcp-servers = "mcp_servers:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
